<?php
/**
 * Matomo - free/libre analytics platform
 *
 * @link https://matomo.org
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 */

namespace Matomo\Scoper\Tests\GeneratedFiles;

use Matomo\Scoper\GeneratedFiles\ProxyAutoloader;
use Matomo\Scoper\Tests\Framework\ComposerTestCase;
use Symfony\Component\Console\Output\NullOutput;

class ProxyAutoloaderTest extends ComposerTestCase
{
    public function test_write_overwritesTheExistingComposerAutoloader()
    {
        $rootPath = $this->setUpTestProject([], [], []);
        $this->putTestProjectFile(
            'vendor/autoload.php',
            <<<EOF
            <?php
            
            // ... autoloader contents ...
            EOF
        );

        $file = new ProxyAutoloader($rootPath . '/vendor', new NullOutput());
        $file->write();

        $this->assertFileExists($rootPath . '/vendor/autoload_original.php');
        $this->assertStringContainsString('... autoloader contents ...', file_get_contents($rootPath . '/vendor/autoload_original.php'));

        $this->assertFileExists($rootPath . '/vendor/autoload.php');
        $this->assertStringContainsString(ProxyAutoloader::PROXY_FILE_MARKER, file_get_contents($rootPath . '/vendor/autoload.php'));
    }

    public function test_write_doesNotWrite_ifAnOriginalComposerAutoloader_isNotFound()
    {
        $rootPath = $this->setUpTestProject([], [], []);
        $this->assertFileDoesNotExist($rootPath . '/vendor/autoload.php');

        $file = new ProxyAutoloader($rootPath . '/vendor', new NullOutput());
        $file->write();

        $this->assertFileDoesNotExist($rootPath . '/vendor/autoload.php');
        $this->assertFileDoesNotExist($rootPath . '/vendor/autoload_original.php');
    }

    public function test_write_regeneratesTheProxy_butKeepsTheOriginalBackup_ifExistingAutoloaderFile_isTheProxyAutoloader()
    {
        $proxyFileMarker = ProxyAutoloader::PROXY_FILE_MARKER;
        $existingAutoloadContents = <<<EOF
        <?php

        $proxyFileMarker

        // an older proxy, generated by a previous version
        EOF;

        $rootPath = $this->setUpTestProject([], [], []);
        $this->putTestProjectFile('vendor/autoload.php', $existingAutoloadContents);

        $file = new ProxyAutoloader($rootPath . '/vendor', new NullOutput());
        $file->write();

        // the real composer autoloader was set aside on the first run, so a proxy must never overwrite that backup
        $this->assertFileDoesNotExist($rootPath . '/vendor/autoload_original.php');

        // the proxy itself is rewritten, so changes to it reach projects that already have one
        $contents = file_get_contents($rootPath . '/vendor/autoload.php');
        $this->assertStringNotContainsString('an older proxy, generated by a previous version', $contents);
        $this->assertStringContainsString(ProxyAutoloader::PROXY_FILE_MARKER, $contents);
    }

    public function test_getContent_isolatesComposerAutoloadFileMarkersAroundThePrefixedAutoloader()
    {
        $rootPath = $this->setUpTestProject([], [], []);

        $file = new ProxyAutoloader($rootPath . '/vendor', new NullOutput());
        $content = $file->getContent();

        $clearMarkers = "\$GLOBALS['__composer_autoload_files'] = [];";
        $requirePrefixed = "require_once __DIR__ . '/prefixed/vendor/autoload.php';";

        $this->assertStringContainsString($clearMarkers, $content);
        $this->assertStringContainsString($requirePrefixed, $content);
        // restored afterwards even if the prefixed autoloader throws
        $this->assertStringContainsString('finally', $content);

        $this->assertLessThan(
            strpos($content, $requirePrefixed),
            strpos($content, $clearMarkers),
            'the markers have to be cleared before the prefixed autoloader runs, or its files are skipped'
        );
    }
}
