<?php
/**
 * Matomo - free/libre analytics platform
 *
 * @link https://matomo.org
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 */

namespace Matomo\Scoper\Tests\GeneratedFiles;

use Matomo\Scoper\GeneratedFiles\ProxyAutoloader;
use Matomo\Scoper\Tests\Framework\ComposerTestCase;
use Symfony\Component\Console\Output\NullOutput;

class ProxyAutoloaderTest extends ComposerTestCase
{
    public function test_write_overwritesTheExistingComposerAutoloader()
    {
        $rootPath = $this->setUpTestProject([], [], []);
        $this->putTestProjectFile(
            'vendor/autoload.php',
            <<<EOF
            <?php
            
            // ... autoloader contents ...
            EOF
        );

        $file = new ProxyAutoloader($rootPath . '/vendor', new NullOutput());
        $file->write();

        $this->assertFileExists($rootPath . '/vendor/autoload_original.php');
        $this->assertStringContainsString('... autoloader contents ...', file_get_contents($rootPath . '/vendor/autoload_original.php'));

        $this->assertFileExists($rootPath . '/vendor/autoload.php');
        $this->assertStringContainsString(ProxyAutoloader::PROXY_FILE_MARKER, file_get_contents($rootPath . '/vendor/autoload.php'));
    }

    public function test_write_doesNotWrite_ifAnOriginalComposerAutoloader_isNotFound()
    {
        $rootPath = $this->setUpTestProject([], [], []);
        $this->assertFileDoesNotExist($rootPath . '/vendor/autoload.php');

        $file = new ProxyAutoloader($rootPath . '/vendor', new NullOutput());
        $file->write();

        $this->assertFileDoesNotExist($rootPath . '/vendor/autoload.php');
        $this->assertFileDoesNotExist($rootPath . '/vendor/autoload_original.php');
    }

    public function test_write_regeneratesTheProxy_butKeepsTheOriginalBackup_ifExistingAutoloaderFile_isTheProxyAutoloader()
    {
        $proxyFileMarker = ProxyAutoloader::PROXY_FILE_MARKER;
        $existingAutoloadContents = <<<EOF
        <?php

        $proxyFileMarker

        // an older proxy, generated by a previous version
        EOF;

        $rootPath = $this->setUpTestProject([], [], []);
        $this->putTestProjectFile('vendor/autoload.php', $existingAutoloadContents);
        $this->putTestProjectFile('vendor/autoload_original.php', "<?php return 'the real composer autoloader';");

        $file = new ProxyAutoloader($rootPath . '/vendor', new NullOutput());
        $file->write();

        // the real composer autoloader was set aside on the first run, so a proxy must never overwrite that backup
        $this->assertSame(
            "<?php return 'the real composer autoloader';",
            file_get_contents($rootPath . '/vendor/autoload_original.php')
        );

        // the proxy itself is rewritten, so changes to it reach projects that already have one
        $contents = file_get_contents($rootPath . '/vendor/autoload.php');
        $this->assertStringNotContainsString('an older proxy, generated by a previous version', $contents);
        $this->assertStringContainsString(ProxyAutoloader::PROXY_FILE_MARKER, $contents);
    }

    public function test_write_producesAProxyThatLoadsPrefixedFileAutoloads_whoseMarkersAnotherProjectAlreadySet()
    {
        // mimics Composer's `files` autoloading: keyed on a hash that prefixing does not change, so a copy of the
        // same package scoped by another plugin has already claimed it
        $vendorPath = $this->setUpProxyExecutionProject(
            <<<'EOF'
            <?php
            if (empty($GLOBALS['__composer_autoload_files']['samehash'])) {
                $GLOBALS['__composer_autoload_files']['samehash'] = true;
                $GLOBALS['prefixedFilesLoaded'] = ($GLOBALS['prefixedFilesLoaded'] ?? 0) + 1;
            }
            EOF
        );

        $GLOBALS['__composer_autoload_files'] = ['samehash' => true];

        try {
            $loader = require $vendorPath . '/autoload.php';

            $this->assertSame('the original loader', $loader);
            $this->assertSame(1, $GLOBALS['prefixedFilesLoaded'] ?? 0, 'the prefixed file autoload entry was skipped');
            $this->assertSame(['samehash' => true], $GLOBALS['__composer_autoload_files']);
        } finally {
            unset($GLOBALS['__composer_autoload_files'], $GLOBALS['prefixedFilesLoaded']);
        }
    }

    public function test_write_producesAProxyThatRestoresTheMarkers_whenThePrefixedAutoloaderThrows()
    {
        $vendorPath = $this->setUpProxyExecutionProject(
            "<?php\n\$GLOBALS['__composer_autoload_files']['clobbered'] = true;\nthrow new \\Exception('prefixed autoloader failure');"
        );

        unset($GLOBALS['__composer_autoload_files']);

        try {
            require $vendorPath . '/autoload.php';
            $this->fail('the prefixed autoloader exception was swallowed');
        } catch (\Exception $ex) {
            $this->assertSame('prefixed autoloader failure', $ex->getMessage());
        } finally {
            $markersAfterFailure = $GLOBALS['__composer_autoload_files'] ?? 'unset';
            unset($GLOBALS['__composer_autoload_files']);
        }

        $this->assertSame('unset', $markersAfterFailure, 'the markers were not restored to their previous, unset state');
    }

    private function setUpProxyExecutionProject(string $prefixedAutoloaderContents): string
    {
        $rootPath = $this->setUpTestProject([], [], []);

        // a fresh path per test, so the proxy's require_once statements actually execute
        $vendorPath = $rootPath . '/exec-' . uniqid() . '/vendor';
        mkdir($vendorPath . '/prefixed/vendor', 0777, true);

        file_put_contents($vendorPath . '/autoload.php', "<?php return 'the original loader';");
        file_put_contents($vendorPath . '/prefixed/vendor/autoload.php', $prefixedAutoloaderContents);

        (new ProxyAutoloader($vendorPath, new NullOutput()))->write();

        return $vendorPath;
    }
}
