<?php
/**
 * Matomo - free/libre analytics platform
 *
 * @link https://matomo.org
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 */

namespace Matomo\Scoper\GeneratedFiles;

use Matomo\Scoper\GeneratedFile;
use Symfony\Component\Console\Output\OutputInterface;

class ProxyAutoloader extends GeneratedFile
{
    const PROXY_FILE_MARKER = '/* this file was generated by the matomo-scoper tool */';

    private string $vendorPath;

    private OutputInterface $output;

    public function __construct(string $vendorPath, OutputInterface $output)
    {
        parent::__construct($vendorPath . '/autoload.php');

        $this->vendorPath = $vendorPath;
        $this->output = $output;
    }

    public function getContent(): ?string
    {
        $proxyFileMarker = self::PROXY_FILE_MARKER;

        $proxyAutoloadContent = <<<EOF
<?php
$proxyFileMarker

\$originalLoader = require_once __DIR__ . DIRECTORY_SEPARATOR . 'autoload_original.php';

if (is_file(__DIR__ . '/prefixed/vendor/autoload.php')) {
    // Composer keys its `files` autoloading by a hash of the package name and the file's path, and prefixing changes
    // neither. Every plugin scoping the same package therefore produces the same key, so without isolating the marker
    // only the first plugin loaded would have its prefixed copies included, and every other plugin's would be
    // silently skipped, leaving their functions and bootstraps undefined.
    \$scoperPreviouslyAutoloadedFiles = \$GLOBALS['__composer_autoload_files'] ?? null;
    \$GLOBALS['__composer_autoload_files'] = [];

    try {
        require_once __DIR__ . '/prefixed/vendor/autoload.php';
    } finally {
        if (\$scoperPreviouslyAutoloadedFiles === null) {
            unset(\$GLOBALS['__composer_autoload_files']);
        } else {
            \$GLOBALS['__composer_autoload_files'] = \$scoperPreviouslyAutoloadedFiles;
        }

        unset(\$scoperPreviouslyAutoloadedFiles);
    }
}

return \$originalLoader;
EOF;

        return $proxyAutoloadContent;
    }

    public function write(): void
    {
        $originalAutoloadPath = $this->vendorPath . '/autoload_original.php';

        if (!is_file($this->outputPath)) {
            $this->output->writeln("<error>Cannot find original composer autoloader!</error>");
            return;
        }

        // Only the first run finds a real composer autoloader here to keep aside; a later run would otherwise back up
        // the proxy over it. The proxy itself is rewritten every time, so changes to it reach plugins that have one.
        if (!$this->isFileAutoloadProxy($this->outputPath)) {
            copy($this->outputPath, $originalAutoloadPath);
        }

        parent::write();
    }

    private function isFileAutoloadProxy(string $autoloadPath): bool
    {
        $contents = file_get_contents($autoloadPath);
        return strpos($contents, self::PROXY_FILE_MARKER) !== false;
    }
}
